spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudservice?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

proxmox:
  host: https://192.168.0.22:8006
  node: byeonghwa
  username: root@pam
  password: skfktkfkd1;
  template-vmid: 201

# VM 설정 - IP 대역 변경
vm:
  ip-range:
    start: 9
    end: 99
  network:
    gateway: 10.8.0.1              # 변경!
    subnet: 10.8.0.0/24            # 변경!
    bridge: vmbr1
  ssh:
    default-username: soongsil       # ubuntu → soongsil

vpn:
  host: http://192.168.100.1:8081